[tool.poetry]
name = "ticketanalysis"
version = "0.1.0"
description = ""
authors = ["david doit <david@doit-intl.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "*"

[tool.poetry.dev-dependencies]
yapf = "*"
mypy = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
