name: main
on:
  push:
    branches:
    - master
    tags:
    - "*"
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: docker build .
  testandlint:
    name: testandlint
    runs-on: ubuntu-latest
    container: python:3.9-slim-buster
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: |
        pip -q install poetry
        poetry install
        poetry run black --check .
        poetry run mypy --ignore-missing-imports .
